spring:
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: account
    placeholders:
      schema: account
    init-sqls: CREATE SCHEMA IF NOT EXISTS account
  jpa:
    hibernate:
    #      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:horizon0-account;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS account;
    username: sa
    password: password
